package manager;

import manager.MeshSimulator;
import mesh.util.Converter;

/**
 * This class defines the Manager configuration GUI
 * @author Feng Zou
 */
public class ManagerGUIConfigBox extends javax.swing.JDialog {
    
    MeshSimulator copyParent;
    
    /** Creates new form ManagerGUIConfigBox
     * @param parent the parent frame
     */
    public ManagerGUIConfigBox(MeshSimulator parent) {
        copyParent = parent;
        initComponents();
        this.setVisible(true);
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPreferenceList = new javax.swing.JPanel();
        jTextFieldFilter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreePreference = new javax.swing.JTree();
        jPanelPreferenceName = new javax.swing.JPanel();
        jLabelPreferenceName = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabelMinimize = new javax.swing.JLabel();
        jCheckBoxSystemTray = new javax.swing.JCheckBox();
        jLabelOthers = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(manager.ManagerApp.class).getContext().getResourceMap(ManagerGUIConfigBox.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanelPreferenceList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPreferenceList.setName("jPanelPreferenceList"); // NOI18N

        jTextFieldFilter.setText("type filter text");
        jTextFieldFilter.setName("jTextFieldFilter"); // NOI18N
        jTextFieldFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFilterActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Preference");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("General");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Others");
        treeNode1.add(treeNode2);
        jTreePreference.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreePreference.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jTreePreference.setName("jTreePreference"); // NOI18N
        jTreePreference.setPreferredSize(new java.awt.Dimension(48, 76));
        jTreePreference.setVisibleRowCount(100);
        jTreePreference.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreePreferenceValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTreePreference);

        javax.swing.GroupLayout jPanelPreferenceListLayout = new javax.swing.GroupLayout(jPanelPreferenceList);
        jPanelPreferenceList.setLayout(jPanelPreferenceListLayout);
        jPanelPreferenceListLayout.setHorizontalGroup(
            jPanelPreferenceListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanelPreferenceListLayout.setVerticalGroup(
            jPanelPreferenceListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPreferenceListLayout.createSequentialGroup()
                .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
        );

        jPanelPreferenceName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPreferenceName.setName("jPanelPreferenceName"); // NOI18N

        jLabelPreferenceName.setFont(resourceMap.getFont("jLabelPreferenceName.font")); // NOI18N
        jLabelPreferenceName.setText("General");
        jLabelPreferenceName.setName("jLabelPreferenceName"); // NOI18N

        javax.swing.GroupLayout jPanelPreferenceNameLayout = new javax.swing.GroupLayout(jPanelPreferenceName);
        jPanelPreferenceName.setLayout(jPanelPreferenceNameLayout);
        jPanelPreferenceNameLayout.setHorizontalGroup(
            jPanelPreferenceNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPreferenceNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPreferenceName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
        );
        jPanelPreferenceNameLayout.setVerticalGroup(
            jPanelPreferenceNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPreferenceName, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLayeredPane1.setName("jLayeredPane1"); // NOI18N

        jLabelMinimize.setText(resourceMap.getString("jLabelMinimize.text")); // NOI18N
        jLabelMinimize.setName("jLabelMinimize"); // NOI18N
        jLabelMinimize.setBounds(10, 10, 70, 30);
        jLayeredPane1.add(jLabelMinimize, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCheckBoxSystemTray.setText(resourceMap.getString("jCheckBoxSystemTray.text")); // NOI18N
        jCheckBoxSystemTray.setName("jCheckBoxSystemTray"); // NOI18N
        jCheckBoxSystemTray.setBounds(90, 10, 90, 30);
        jLayeredPane1.add(jCheckBoxSystemTray, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabelOthers.setText(resourceMap.getString("jLabelOthers.text")); // NOI18N
        jLabelOthers.setName("jLabelOthers"); // NOI18N
        jLabelOthers.setVisible(false);
        jLabelOthers.setBounds(10, 10, 470, 110);
        jLayeredPane1.add(jLabelOthers, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setName("jPanel1"); // NOI18N

        jButtonOK.setText("OK");
        jButtonOK.setName("jButtonOK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.setName("jButtonCancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(431, Short.MAX_VALUE)
                .addComponent(jButtonOK)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancel))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancel, jButtonOK});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOK)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonCancel, jButtonOK});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelPreferenceList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                            .addComponent(jPanelPreferenceName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelPreferenceList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelPreferenceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)))
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     *  need to change this part later
     */
    
    
    private void jTextFieldFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFilterActionPerformed
        
    }//GEN-LAST:event_jTextFieldFilterActionPerformed

    private void jTreePreferenceValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreePreferenceValueChanged
        
        javax.swing.tree.DefaultMutableTreeNode node = new javax.swing.tree.DefaultMutableTreeNode(this.jTreePreference.getLastSelectedPathComponent());
        this.jLabelPreferenceName.setText(node.toString());

        //General Pane
        if(((String)node.toString()).compareTo("General")== 0)
        {
            jLabelOthers.setVisible(false);
            jLabelMinimize.setVisible(true);
            jCheckBoxSystemTray.setVisible(true);
        }

        //Others Pane (for Future Use)
        if(((String)node.toString()).compareTo("Others")== 0)
        {
            jLabelMinimize.setVisible(false);
            jCheckBoxSystemTray.setVisible(false);
            jLabelOthers.setVisible(true);
        }
    }//GEN-LAST:event_jTreePreferenceValueChanged

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed

        //Set Minimizing to System Tray true
        if(jCheckBoxSystemTray.isVisible() && jCheckBoxSystemTray.isSelected()) {
            this.copyParent.SetToSystemTray();
        }
        else
        {
            if(jCheckBoxSystemTray.isVisible()&& !jCheckBoxSystemTray.isSelected())
                this.copyParent.SetToTaskBar();
            else
            {
                if(jLabelOthers.isVisible())
                {
                    //Fill Your Code Here
                }
            }
        }

        this.dispose();
}//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JCheckBox jCheckBoxSystemTray;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelOthers;
    private javax.swing.JLabel jLabelPreferenceName;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPreferenceList;
    private javax.swing.JPanel jPanelPreferenceName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldFilter;
    private javax.swing.JTree jTreePreference;
    // End of variables declaration//GEN-END:variables
}
