package manager.guiApp;

import org.jdesktop.application.Action;

/**
 * this class defines the network manager about box GUI
 * @author Song Han
 */
public class ManagerAboutBox extends javax.swing.JDialog {

    /**
     * constructor function
     * @param parent the parent frame
     */
    public ManagerAboutBox(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
        displayUsedFreeComponents();
    }

    /**
     * this function sets the ManagerCore major version and minor version
     * @param major the major version number of the gateway
     * @param minor the minor version number of the gateway
     */
    static public void SetManagerCoreVersion(String version)
    {
        managerCoreVersion = version;
    }
    
    /**
     * this function sets the gateway major version and minor version
     * @param major the major version number of the gateway
     * @param minor the minor version number of the gateway
     */
    static public void SetGatewayVersion(String version)
    {
        gatewayVersion = version;
    }

    /**
     * this function sets the AP major version and minor version
     * @param major the major version number of the AP
     * @param minor the minor version number of the AP
     */
    static public void SetApVersion(int major, int minor, int svn)
    {
        apMajorVersion = major;
        apMinorVersion = minor;
        apSvnVersion = svn;
    }

    /**
     * this function closes the network manager about box
     */
    @Action public void closeAboutBox() {
        dispose();
    }
    
    /**
     * Update / Displays the free components that GW / NM / GUI uses.
     * The text is inserted using the Netbeans GUI builder
     */
    private void displayUsedFreeComponents()
    {
        //FYI, the grey color of the textArea is 240,240,240
        javax.swing.JTextArea display = usedComponentsTextArea;
        display.setCaretPosition(0); // scroll all the way up
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        javax.swing.JLabel lbTitle = new javax.swing.JLabel();
        javax.swing.JLabel lbVersionCap = new javax.swing.JLabel();
        javax.swing.JLabel lbManagerVersion = new javax.swing.JLabel();
        javax.swing.JLabel lbVendorCap = new javax.swing.JLabel();
        javax.swing.JLabel lbVendor = new javax.swing.JLabel();
        javax.swing.JLabel lbHomepageCap = new javax.swing.JLabel();
        javax.swing.JLabel appHomepageLabel = new javax.swing.JLabel();
        javax.swing.JLabel appDescLabel = new javax.swing.JLabel();
        javax.swing.JLabel imageLabel = new javax.swing.JLabel();
        lbManagerVersionCap = new javax.swing.JLabel();
        Gateway = new javax.swing.JLabel();
        lbGatewayVersion = new javax.swing.JLabel();
        lbHomepage = new javax.swing.JLabel();
        lbApVersionCap = new javax.swing.JLabel();
        lbApVersion = new javax.swing.JLabel();
        lbManagerCoreVersionCap = new javax.swing.JLabel();
        lbManagerCoreVersion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usedComponentsTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(manager.ManagerApp.class).getContext().getResourceMap(ManagerAboutBox.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setBackground(resourceMap.getColor("aboutBox.background")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DialogShownHandler(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(manager.ManagerApp.class).getContext().getActionMap(ManagerAboutBox.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N

        lbTitle.setFont(lbTitle.getFont().deriveFont(lbTitle.getFont().getStyle() | java.awt.Font.BOLD, lbTitle.getFont().getSize()+4));
        lbTitle.setText(resourceMap.getString("Application.title")); // NOI18N
        lbTitle.setName("lbTitle"); // NOI18N

        lbVersionCap.setFont(lbVersionCap.getFont().deriveFont(lbVersionCap.getFont().getStyle() | java.awt.Font.BOLD));
        lbVersionCap.setText(resourceMap.getString("lbVersionCap.text")); // NOI18N
        lbVersionCap.setName("lbVersionCap"); // NOI18N

        lbManagerVersion.setText(resourceMap.getString("Application.version")); // NOI18N
        lbManagerVersion.setName("lbManagerVersion"); // NOI18N

        lbVendorCap.setFont(lbVendorCap.getFont().deriveFont(lbVendorCap.getFont().getStyle() | java.awt.Font.BOLD));
        lbVendorCap.setText(resourceMap.getString("lbVendorCap.text")); // NOI18N
        lbVendorCap.setName("lbVendorCap"); // NOI18N

        lbVendor.setText(resourceMap.getString("Application.vendor")); // NOI18N
        lbVendor.setName("lbVendor"); // NOI18N

        lbHomepageCap.setFont(lbHomepageCap.getFont().deriveFont(lbHomepageCap.getFont().getStyle() | java.awt.Font.BOLD));
        lbHomepageCap.setText(resourceMap.getString("lbHomepageCap.text")); // NOI18N
        lbHomepageCap.setName("lbHomepageCap"); // NOI18N

        appHomepageLabel.setText(resourceMap.getString("Application.homepage")); // NOI18N
        appHomepageLabel.setName("appHomepageLabel"); // NOI18N

        appDescLabel.setText(resourceMap.getString("appDescLabel.text")); // NOI18N
        appDescLabel.setName("appDescLabel"); // NOI18N

        imageLabel.setIcon(resourceMap.getIcon("imageLabel.icon")); // NOI18N
        imageLabel.setName("imageLabel"); // NOI18N

        lbManagerVersionCap.setText(resourceMap.getString("lbManagerVersionCap.text")); // NOI18N
        lbManagerVersionCap.setName("lbManagerVersionCap"); // NOI18N

        Gateway.setText(resourceMap.getString("Gateway.text")); // NOI18N
        Gateway.setName("Gateway"); // NOI18N

        lbGatewayVersion.setText(resourceMap.getString("lbGatewayVersion.text")); // NOI18N
        lbGatewayVersion.setName("lbGatewayVersion"); // NOI18N

        lbHomepage.setText(resourceMap.getString("lbHomepage.text")); // NOI18N
        lbHomepage.setName("lbHomepage"); // NOI18N

        lbApVersionCap.setText(resourceMap.getString("lbApVersionCap.text")); // NOI18N
        lbApVersionCap.setName("lbApVersionCap"); // NOI18N

        lbApVersion.setText(resourceMap.getString("lbApVersion.text")); // NOI18N
        lbApVersion.setName("lbApVersion"); // NOI18N

        lbManagerCoreVersionCap.setText(resourceMap.getString("lbManagerCoreVersionCap.text")); // NOI18N
        lbManagerCoreVersionCap.setName("lbManagerCoreVersionCap"); // NOI18N

        lbManagerCoreVersion.setText(resourceMap.getString("lbManagerCoreVersion.text")); // NOI18N
        lbManagerCoreVersion.setName("lbManagerCoreVersion"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        usedComponentsTextArea.setBackground(resourceMap.getColor("usedComponentsTextArea.background")); // NOI18N
        usedComponentsTextArea.setColumns(20);
        usedComponentsTextArea.setEditable(false);
        usedComponentsTextArea.setFont(resourceMap.getFont("usedComponentsTextArea.font")); // NOI18N
        usedComponentsTextArea.setRows(5);
        usedComponentsTextArea.setText(resourceMap.getString("usedComponentsTextArea.text")); // NOI18N
        usedComponentsTextArea.setName("usedComponentsTextArea"); // NOI18N
        jScrollPane1.setViewportView(usedComponentsTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitle)
                            .addComponent(appDescLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbVersionCap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(appHomepageLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Gateway, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                        .addComponent(lbGatewayVersion))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbManagerVersionCap)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                        .addComponent(lbManagerVersion))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbApVersionCap)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                                        .addComponent(lbApVersion))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbManagerCoreVersionCap)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                                        .addComponent(lbManagerCoreVersion))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbHomepageCap)
                                .addGap(18, 18, 18)
                                .addComponent(lbHomepage))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbVendorCap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbVendor))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(434, Short.MAX_VALUE)
                        .addComponent(closeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appDescLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbVersionCap)
                            .addComponent(lbManagerVersionCap)
                            .addComponent(lbManagerVersion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbManagerCoreVersion)
                            .addComponent(lbManagerCoreVersionCap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(appHomepageLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbGatewayVersion)
                                    .addComponent(Gateway))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbApVersionCap)
                                    .addComponent(lbApVersion))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbVendorCap)
                            .addComponent(lbVendor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHomepage)
                            .addComponent(lbHomepageCap)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageLabel)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName(resourceMap.getString("aboutBox.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DialogShownHandler(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DialogShownHandler
        if (managerCoreVersion != null)
            this.lbManagerCoreVersion.setText(managerCoreVersion);
        else
            this.lbGatewayVersion.setText("?");
        
        if (gatewayVersion != null)
            this.lbGatewayVersion.setText(gatewayVersion);
        else
            this.lbGatewayVersion.setText("?");

        if (apMajorVersion >= 0)
            this.lbApVersion.setText(apMajorVersion + "." + apMinorVersion + "." + apSvnVersion);
        else
            this.lbApVersion.setText("?");
    }//GEN-LAST:event_DialogShownHandler
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gateway;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbApVersion;
    private javax.swing.JLabel lbApVersionCap;
    private javax.swing.JLabel lbGatewayVersion;
    private javax.swing.JLabel lbHomepage;
    private javax.swing.JLabel lbManagerCoreVersion;
    private javax.swing.JLabel lbManagerCoreVersionCap;
    private javax.swing.JLabel lbManagerVersionCap;
    private javax.swing.JTextArea usedComponentsTextArea;
    // End of variables declaration//GEN-END:variables

    static private String managerCoreVersion = null;
    
    static private String gatewayVersion = null;
    
    static private int apMajorVersion = -1;
    static private int apMinorVersion = 0;
    static private int apSvnVersion = 0;
}
